### (https://www.bilibili.com/video/av50549362/?p=8)

In [1]:
import torch

In [2]:
s = torch.randn(2,3) #正态分布随机数，默认均值0，方差1。2行3列

In [3]:
s.type()

'torch.FloatTensor'

In [4]:
s

tensor([[-1.2637, -0.9648, -2.2581],
        [-0.5274,  0.2739,  1.0637]])

In [6]:
isinstance(s, torch.FloatTensor)

True

---

# 标量的表示

## 常用用途：计算Loss

In [7]:
scalar1 = torch.tensor(1.5)
scalar1

tensor(1.5000)

In [8]:
scalar1.size()

torch.Size([])

In [9]:
scalar1.shape

torch.Size([])

In [10]:
len(scalar1.shape)

0

---
# 1维张量

## 常用用途： bias

In [11]:
t1 = torch.tensor([1.2])

In [12]:
t1.size()

torch.Size([1])

In [14]:
t1.shape

torch.Size([1])

In [15]:
len(t1.shape)

1

In [16]:
t2 = torch.tensor([1.2, 2.5])

In [17]:
t2.shape

torch.Size([2])

In [18]:
torch.FloatTensor(2)

tensor([0., 0.])

In [20]:
import numpy as np

In [21]:
data1 = np.ones(3)

In [22]:
torch.from_numpy(data1)

tensor([1., 1., 1.], dtype=torch.float64)

In [23]:
a = torch.randn(2, 3)
a

tensor([[-0.3378, -0.2430, -1.6126],
        [-0.0817, -0.4541,  0.4189]])

In [25]:
b = torch.FloatTensor(2, 3) #初始化的数据也是随机产生的
b

tensor([[0.0000e+00, 0.0000e+00, 1.3236e+22],
        [3.4013e+21, 1.0325e-08, 3.4164e+21]])

In [26]:
a.size(0)

2

In [27]:
a.size(1)

3

In [28]:
a.shape[1]

3

## MINST 图片处理
### batch为1的 tensor 为[784]..
### 2维张量 ：batch为n的tensor为[n, 784]



In [30]:
a = torch.rand(2,3,4)
a

tensor([[[0.5970, 0.6053, 0.8616, 0.8763],
         [0.3080, 0.4989, 0.7207, 0.1877],
         [0.8170, 0.9212, 0.8805, 0.5005]],

        [[0.7775, 0.2326, 0.3001, 0.7801],
         [0.3675, 0.2901, 0.8310, 0.4864],
         [0.8471, 0.2840, 0.1179, 0.5536]]])

In [33]:
list(a.shape)

[2, 3, 4]

---
### 3 维张量使用场景：
#### 例如：RNN 每句话10个单词，每个单词为100维向量，每次输入20句话，那么用张量表示 [10, 20, 100]
#### RNN 比较适合文字处理

---
### 4维张量使用场景
#### CNN 适合图片处理

In [36]:
a = torch.rand(2, 3, 28, 28) 
# 3-代表颜色通道，如果是灰度图片，那么就是1

In [37]:
a.numel() #数据量 number of element

4704

In [38]:
a.dim()

4